FROM ubuntu:18.04

###############################################################################
# set up of GUI environment
###############################################################################

# To verify toga dependencies we want a plain ubuntu container to ensure no
# dependencies are pre-installed which usually should be installed by the user.
# On the other hand we need a GUI environment. We use LXDE, because it's a
# fairly minimalistic one. The following lines were copied from
# https://github.com/mviereck/dockerfile-x11docker-lxde/blob/master/Dockerfile:
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      policykit-1-gnome && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      dbus-x11 \
      lxde \
      lxlauncher \
      lxmenu-data \
      lxtask \
      procps \
      psmisc

# OpenGL / MESA
# adds 68 MB to image, disabled
#RUN apt-get install -y mesa-utils mesa-utils-extra libxv1 


# GTK 2 and 3 settings for icons and style, wallpaper
RUN echo '\n\
gtk-theme-name="Raleigh"\n\
gtk-icon-theme-name="nuoveXT2"\n\
' > /etc/skel/.gtkrc-2.0 && \
\
mkdir -p /etc/skel/.config/gtk-3.0 && \
echo '\n\
[Settings]\n\
gtk-theme-name="Raleigh"\n\
gtk-icon-theme-name="nuoveXT2"\n\
' > /etc/skel/.config/gtk-3.0/settings.ini && \
\
mkdir -p /etc/skel/.config/pcmanfm/LXDE && \
echo '\n\
[*]\n\
wallpaper_mode=stretch\n\
wallpaper_common=1\n\
wallpaper=/usr/share/lxde/wallpapers/lxde_blue.jpg\n\
' > /etc/skel/.config/pcmanfm/LXDE/desktop-items-0.conf && \
\
mkdir -p /etc/skel/.config/libfm && \
echo '\n\
[config]\n\
quick_exec=1\n\
terminal=lxterminal\n\
' > /etc/skel/.config/libfm/libfm.conf && \
\
mkdir -p /etc/skel/.config/openbox/ && \
echo '<?xml version="1.0" encoding="UTF-8"?>\n\
<theme>\n\
  <name>Clearlooks</name>\n\
</theme>\n\
' > /etc/skel/.config/openbox/lxde-rc.xml && \
\
mkdir -p /etc/skel/.config/ && \
echo '[Added Associations]\n\
text/plain=mousepad.desktop;\n\
' > /etc/skel/.config/mimeapps.list

RUN echo "#! /bin/bash\n\
echo 'x11docker/lxde: If the panel does not show an approbate menu\n\
  and you encounter high CPU usage (seen with kata-runtime),\n\
  please run with option --init=systemd.\n\
' >&2 \n\
startlxde\n\
" >/usr/local/bin/start && chmod +x /usr/local/bin/start

CMD ["/usr/local/bin/start"]

###############################################################################
# toga-specific setup
###############################################################################

# not required, but just in case...
USER root
COPY setup-container-as-root.sh /root/bin/
RUN /root/bin/setup-container-as-root.sh /home/user/toga-dependency-test/

# USER user would have no effect and the copied files would still be owned by
# root, so don't bother and instead change ownership at the end
COPY helloworld.py /home/user/toga-dependency-test/
COPY farenheit_celcius.py /home/user/toga-dependency-test/
# TODO(KNR): For reasons I haven't analyzed the nested_boxes.py application
# doesn't find the icons...
COPY icons/ /home/user/toga-dependency-test/icons/
COPY nested_boxes.py /home/user/toga-dependency-test/
RUN chown -R user:user /home/user/toga-dependency-test/

USER user
COPY setup-container-as-user.sh /home/user/bin/
RUN /home/user/bin/setup-container-as-user.sh /home/user/toga-dependency-test/