#!/bin/bash

set -eo pipefail

PROJECT_DIRECTORY="$1"
if [[ "${PROJECT_DIRECTORY}" == "" ]]; then
  echo "Error: no project directory parameter defined."
  exit 1
fi

# necessary because the package list in the base image is empty
apt update

# install helpers to debug the setup for convenience, not strictly required
apt install --yes sudo vim

# install prerequisites not explicitly listed in the tutorial
apt install --yes python3 python3-pip python3-venv

# install dependencies listed in the tutorial in order to test them
apt install --yes python3-dev libgirepository1.0-dev python3-cairo libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0

# Set up a regular user for more realistic conditions, because certain commands
# behave different as root. Possibly not necessary, but just to be sure.
#
# The password hash was generated by: openssl passwd -1 "togatest"
# see https://blog.sleeplessbeastie.eu/2015/09/28/how-to-programmatically-create-system-user-with-defined-password/
#
# pass the password hash like in https://stackoverflow.com/a/61603505/1776679
useradd -ms /bin/bash -p '$1$Z0Ri1XrC$h3KoP0dHO5IGTlE4nhX7n1' user
usermod -aG sudo user

# create the project directory ourselves so that we can pass ownership to user
mkdir -p "${PROJECT_DIRECTORY}"
chown user:user "${PROJECT_DIRECTORY}"