#!/bin/bash

set -eo pipefail

PROJECT_DIRECTORY="$1"
if [[ "${PROJECT_DIRECTORY}" == "" ]]; then
  echo "Error: no project directory parameter defined."
  exit 1
fi

# make sure the docker build command is not blocked by interactions
export DEBIAN_FRONTEND=noninteractive

# install helpers to debug the setup for convenience, not strictly required
apt install --yes --no-install-recommends vim

# install prerequisites not explicitly listed in the tutorial
apt install --yes --no-install-recommends python3 python3-pip python3-venv

UBUNTU_VERSION="$(cat /etc/*release | grep VERSION_ID)"
WEBKIT_PACKAGES=""
if [[ "${UBUNTU_VERSION}" == 'VERSION_ID="18.04"' ]]; then
  # install dependencies listed in the briefcase-template
  # https://github.com/beeware/briefcase-template/blob/v0.3/%7B%7B%20cookiecutter.app_name%20%7D%7D/pyproject.toml
  WEBKIT_PACKAGES="libwebkitgtk-3.0-0 gir1.2-webkit-3.0"
elif [[ "${UBUNTU_VERSION}" == 'VERSION_ID="20.04"' ]]; then
  WEBKIT_PACKAGES="libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0"
else
  echo "Error: Linux or Ubuntu version ${UBUNTU_VERSION} is not supported."
  exit 1
fi
# extended by python3-dev, otherwise "pip3 install pycairo" would fail
apt install --yes --no-install-recommends python3-dev libgirepository1.0-dev libcairo2-dev libpango1.0-dev ${WEBKIT_PACKAGES}

# Set up a regular user for more realistic conditions, because certain commands
# behave different as root. Possibly not necessary, but just to be sure.
#
# The password hash was generated by: openssl passwd -1 "togatest"
# see https://blog.sleeplessbeastie.eu/2015/09/28/how-to-programmatically-create-system-user-with-defined-password/
#
# pass the password hash like in https://stackoverflow.com/a/61603505/1776679
useradd -ms /bin/bash -p '$1$Z0Ri1XrC$h3KoP0dHO5IGTlE4nhX7n1' user

# create the project directory ourselves so that we can pass ownership to user
mkdir -p "${PROJECT_DIRECTORY}"
chown user:user "${PROJECT_DIRECTORY}"